//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditWorks.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CreditWorksEntities : DbContext
    {
        public CreditWorksEntities()
            : base("name=CreditWorksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vehicle_Category> Vehicle_Category { get; set; }
        public virtual DbSet<Vehicle_Manufacturer> Vehicle_Manufacturer { get; set; }
        public virtual DbSet<VehicleInfo> VehicleInfo { get; set; }
    }
}
